import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
 
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils"
import "@/theme/theme.scss";
import { Footer } from "@/components";
import Navbar from "@/components/Navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Style Dictionary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body className={cn(inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider></body>
    </html>
  );
}
